const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
const $ = id => document.getElementById(id);
const ui = { wave: $('wave'), score: $('score'), health: $('healthText'), bar: $('healthBar'), start: $('startCard'), end: $('endCard'), endTitle: $('endTitle'), endText: $('endText'), cross: $('crosshair') };
let w, h, aim = {x: 0, y:0}, enemies=[], shots=[], particles=[], running=false, paused=false, score=0, health=100, wave=1, spawnTimer=0, last=0, shake=0;
function resize(){ const r=canvas.getBoundingClientRect(); const d=devicePixelRatio||1; canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);w=r.width;h=r.height; aim.x=w*.5;aim.y=h*.5; }
addEventListener('resize',resize); resize();
function random(a,b){return a+Math.random()*(b-a)}
function makeEnemy(){ const s=random(22,38), side=Math.random()<.5; enemies.push({x:side?random(25,w*.26):random(w*.74,w-25),y:random(h*.28,h*.76),s, hp:2+(wave>3?1:0),speed:random(7,17)+wave*2, wobble:random(0,6.3), shot:random(.7,1.8)}); }
function burst(x,y,color,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:random(-110,110),vy:random(-100,35),life:random(.25,.6),color,size:random(1,4)})}
function fire(){if(!running||paused)return;shots.push({x:aim.x,y:aim.y,life:.08});shake=5; const hit=enemies.reduce((best,e)=>{let d=Math.hypot(e.x-aim.x,e.y-aim.y);return d<(e.s+25)&&( !best||d<best.d)?{e,d}:best},null);if(hit){hit.e.hp--;burst(hit.e.x,hit.e.y,'#e3b34a');if(hit.e.hp<=0){score+=100;enemies=enemies.filter(e=>e!==hit.e);burst(hit.e.x,hit.e.y,'#bf4935',24)}}updateUI();}
function damage(){health=Math.max(0,health-9);shake=11;updateUI();if(!health){running=false;finish(false)}}
function updateUI(){ui.score.textContent=String(score).padStart(4,'0');ui.wave.textContent=wave;ui.health.textContent=health;ui.bar.style.width=health+'%';}
function finish(win){ui.end.classList.remove('hidden');ui.endTitle.textContent=win?'Sector secured':'You were overrun';ui.endText.textContent=win?`Final score: ${score}`:`Final score: ${score} — rally and try again.`}
function reset(){enemies=[];shots=[];particles=[];score=0;health=100;wave=1;spawnTimer=0;running=true;paused=false;ui.start.classList.add('hidden');ui.end.classList.add('hidden');updateUI()}
function drawBackground(){let sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#607a80');sky.addColorStop(.52,'#b28e63');sky.addColorStop(1,'#443e2d');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle='#73877e';ctx.beginPath();ctx.moveTo(0,h*.42);for(let x=0;x<=w;x+=60)ctx.lineTo(x,h*.35+Math.sin(x*.02)*25);ctx.lineTo(w,h*.62);ctx.lineTo(0,h*.62);ctx.fill();ctx.fillStyle='#4e5b4d';ctx.fillRect(0,h*.51,w,h*.12);ctx.fillStyle='#5d4a32';ctx.fillRect(0,h*.63,w,h*.37);for(let i=0;i<20;i++){ctx.fillStyle=i%2?'#846542':'#392f22';ctx.fillRect((i*79)%w,h*.68+(i%5)*19,random(24,72),random(3,9));}ctx.fillStyle='rgba(234,197,121,.24)';ctx.fillRect(0,h*.52,w,3)}
function drawEnemy(e,t){e.wobble+=t*.002;e.x+=Math.sin(e.wobble)*.17;let bob=Math.sin(e.wobble*1.7)*3;ctx.save();ctx.translate(e.x,e.y+bob);ctx.fillStyle='#242c27';ctx.fillRect(-e.s*.35,-e.s*.05,e.s*.7,e.s*.9);ctx.fillStyle='#69755a';ctx.beginPath();ctx.arc(0,-e.s*.34,e.s*.31,0,7);ctx.fill();ctx.fillStyle='#1c2621';ctx.fillRect(-e.s*.52,e.s*.19,e.s*1.04,e.s*.14);ctx.strokeStyle='#20251e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(e.s*.3,e.s*.22);ctx.lineTo(e.s*.92,e.s*.06);ctx.stroke();ctx.fillStyle='#e7bd59';ctx.fillRect(-e.s*.13,-e.s*.4,e.s*.26,3);ctx.restore()}
function loop(now){let dt=Math.min(.04,(now-last)/1000||0);last=now;ctx.save();if(shake){ctx.translate(random(-shake,shake),random(-shake,shake));shake*=.85}drawBackground();if(running&&!paused){spawnTimer-=dt;if(spawnTimer<=0){makeEnemy();spawnTimer=Math.max(.42,1.4-wave*.09)}enemies.forEach(e=>{e.y+=e.speed*dt;e.shot-=dt;if(e.shot<0){damage();e.shot=random(1.3,2.7)}drawEnemy(e,now)});particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt;p.life-=dt;ctx.fillStyle=p.color;ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillRect(p.x,p.y,p.size,p.size)});particles=particles.filter(p=>p.life>0);shots.forEach(s=>{ctx.strokeStyle='#fff0ad';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(w*.5,h);ctx.lineTo(s.x,s.y);ctx.stroke();s.life-=dt});shots=shots.filter(s=>s.life>0);if(score>=wave*900){wave++;score+=50;enemies=[];spawnTimer=.7;updateUI()}if(wave>7){running=false;finish(true)}}else enemies.forEach(e=>drawEnemy(e,now));ctx.restore();if(paused){ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(0,0,w,h);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='700 32px Barlow Condensed';ctx.fillText('PAUSED',w/2,h/2)}requestAnimationFrame(loop)}requestAnimationFrame(loop);
function point(e){const r=canvas.getBoundingClientRect(), p=e.touches?e.touches[0]:e;aim.x=p.clientX-r.left;aim.y=p.clientY-r.top;ui.cross.style.left=aim.x+'px';ui.cross.style.top=aim.y+'px'}
canvas.addEventListener('pointermove',point);canvas.addEventListener('pointerdown',e=>{point(e);fire()});canvas.addEventListener('touchmove',e=>{e.preventDefault();point(e)},{passive:false});$('fireButton').addEventListener('pointerdown',e=>{e.preventDefault();fire()});$('startButton').onclick=reset;$('restartButton').onclick=reset;$('pauseButton').onclick=()=>{if(running)paused=!paused};addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();fire()}if(e.code==='KeyP'&&running)paused=!paused});
